---
galaxy_info:
  author: ""
  description: Ansible playbook for deploying PowerBroker Identity Services PBIS Open Edition for RedHat/CentOS/Ubuntu
  company: 
  license: MIT
  min_ansible_version: 1.2

  platforms:
  - name: EL
    versions:
     - 6
     - 7
  - name: Ubuntu
    versions:
     - 'trusty'
     - 'xenial'

  categories:
  - system

  dependencies: []
