---
# tasks file for pbis on Redhat
# repo info available: http://repo.pbis.beyondtrust.com/yum.html

  - name: Redhat | add BeyondTrust PBIS open yum repo
    yum_repository:
      name: pbiso
      description: PBIS-Open Repository
      baseurl: http://repo.pbis.beyondtrust.com/yum/pbiso/$basearch
      gpgkey: http://repo.pbis.beyondtrust.com/yum/RPM-GPG-KEY-pbis
      gpgcheck: yes
      enabled: yes

  - name: Redhat | yum install pbis-open
    yum: name=pbis-open state=latest