---
# handlers file for pbis
  - name: config pbis domain
    command: /opt/pbis/bin/config AssumeDefaultDomain {{ assume_default_domain }}

  - name: config pbis shell
    command: /opt/pbis/bin/config LoginShellTemplate {{ login_shell_template }}

  - name: config pbis homedirtemplate
    command: /opt/pbis/bin/config HomeDirTemplate {{ homedir_template }}

  - name: config pbis userdomainprefix
    command: /opt/pbis/bin/config UserDomainPrefix {{ domain_netbios }}